syntax = "proto3";


import "google/protobuf/empty.proto";


service AgentService {
    rpc hello(HelloRequest) returns (HelloResponse);
    rpc get_angle(AngleRequest) returns (AngleResponse);
    rpc set_angle(SetAngleRequest) returns (google.protobuf.Empty); //maybe hier ein empty hin
    rpc get_posture(GetPostureRequest) returns (GetPostureResponse);
    rpc execute_keyframes(ExecuteKeyframesRequest) returns (google.protobuf.Empty);
    rpc get_transform(TransformRequest) returns (TransformResponse);
    rpc set_transform(SetTransformRequest) returns (SetTransformResponse);
}

message HelloRequest{
    string name = 1;
}

message HelloResponse{
    string hello_answer = 1;
}

message AngleRequest{
    string joint_name = 1;
}

message AngleResponse{
    double angle = 1;
}

message SetAngleRequest{
    string joint_name = 1;
    double angle = 2;
}

message GetPostureRequest{}

message GetPostureResponse{
    string posture = 1;
}

message ExecuteKeyframesRequest{
    string keyframes = 1; //<- falls json in der Umsetzung nervt
    //string keyframes_json = 1;
    
}

message TransformRequest{
    string name = 1;
}

message Transform{
    repeated double data = 1;
    int32 rows = 2;
    int32 cols = 3;
}
 
message TransformResponse{
    string name = 1;
    Transform transform = 2;

}

message SetTransformRequest{
    string effector_name = 1;
    Transform transform = 2;
}


message SetTransformResponse{
    repeated string joint_names = 1;
    repeated double joint_angles = 2;

}